services:
  - type: web
    name: trivio
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node backend/servidor.js
    envVars:
      - key: NODE_ENV
        value: production
